version: '3'

services:
  mongo_config_server:
    container_name: mongo_config_server
    image: mongo
    restart: unless-stopped
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 27018:27017
    volumes:
      - mongo_configs:/data/db

  mongo_shard:
    container_name: mongo_shard
    image: mongo
    restart: unless-stopped
    command: mongod --shardsvr --port 27017 --dbpath /data/db
    ports:
      - 27019:27017
    volumes:
      - mongo_shard:/data/db
  
  mongo_router:
    container_name: mongo_router
    image: mongo
    restart: unless-stopped
    command: mongos --auth --configdb cfgrs/127.0.0.1:27018 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 27017:27017
    volumes:
      - mongo_router:/data/db

volumes:
  mongo_configs: {}
  mongo_shard: {}
  mongo_router: {}